CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS configs (
    id BIGSERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    auto_hunt BOOLEAN NOT NULL DEFAULT TRUE,
    auto_heal BOOLEAN NOT NULL DEFAULT TRUE,
    heal_percent INTEGER NOT NULL DEFAULT 40,
    auto_buy_potions BOOLEAN NOT NULL DEFAULT TRUE,
    min_potions INTEGER NOT NULL DEFAULT 5,
    auto_dungeon BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS inventory (
    id BIGSERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    potions INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dungeons (
    id BIGSERIAL PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS logs (
    id BIGSERIAL PRIMARY KEY,
    level TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
